---
- name: Download and extract the latest release of eksctl in linux
  get_url:
    url: "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
    dest: "{{tools_dir_loc}}/k8-tools"
  register: eksctl_download
  tags: 
    - eksctl_download

- debug: msg="eksctl installed."
  when: eksctl_download.changed
  tags: eksctl_download

- name: Unarchive the tar.gz file
  unarchive:
    src: "{{tools_dir_loc}}/k8-tools/eksctl_Linux_amd64.tar.gz"
    dest: "{{tools_dir_loc}}/k8-tools"
    remote_src: yes
- name: Copy the installed file to /usr/bin
  shell: cp {{tools_dir_loc}}/k8-tools/eksctl /usr/bin

  register: eksctl_copy

- name: Check eksctl version
  shell: eksctl version
  register: eksctl_version
  tags:
    - eksctl_download

- debug: msg="eksctl is installed with version {{eksctl_version.stdout}}"  