---
- name: Install kubectl binary with get_url on remote_user_linux
  get_url:
    url: "https://dl.k8s.io/release/{{kubectl_version}}/bin/linux/amd64/kubectl"
    dest: "{{tools_dir_loc}}/k8-tools"
  register: kubectl_download
  tags: 
    - kubectl_download

- debug: msg="Kubectl binary installed."
  when: kubectl_download.changed
  tags: kubectl_download

- name: Install kubectl
  shell: install -o root -g root -m 0755 {{tools_dir_loc}}/k8-tools/kubectl /usr/bin
  register: kubectl_install
  tags: kubectl_download

- debug: msg="Kubectl installed."
  when: kubectl_install.changed
  tags: kubectl_download

- name: Check Kubectl version
  shell: kubectl version --client --output=yaml
  register: kubectl_version
  tags:
    - kubectl_download
  when: kubectl_install.changed

- debug: msg="Kubectl is installed with version {{kubectl_version}}"  