---
- name: Create a directory
  file:
    #new_dir_name needs to be passed through command line using --extra-vars flag
    #tools_dir_loc is referenced from vars_files.
    path: "{{tools_dir_loc}}/{{new_dir_name}}"
    state: directory
  register: dir_status
  tags: 
    - create_dir
    - aws_install_zip
    - kubectl_download

- debug: msg="Directory created at {{tools_dir_loc}}"
  when: dir_status.changed
  tags: 
    - create_dir
    - aws_install_zip
    - kubectl_download

- debug: msg="There is already a folder name {{new_dir_name}} at {{tools_dir_loc}}."
  when: dir_status.changed == false
  tags: 
    - create_dir
    - aws_install_zip
    - kubectl_download