---
- name: Remove a directory
  file:
    path: "{{tools_dir_loc}}/{{rm_dir_name}}"
    state: absent
  register: dir_status
  tags: remove_dir

- debug: msg="Directory deleted successfully at {{tools_dir_loc}}."
  when: dir_status.changed
  tags: remove_dir

- debug: msg="There is no folder named {{rm_dir_name}} at {{tools_dir_loc}}."
  when: dir_status.changed == false
  tags: remove_dir