--- 
- name: aws-cli #name of playbook
  hosts: ansible_clients #system at which playbook will be executed
  remote_user: ec2-user
  become: true #you need to become root to provide escalated escalations
  tasks:
    - name: Create a directory "awscli" to store the zip
      file:
        path: "/usr/bin/tools/aws-cli"
        state: directory
      register: dir_status
      
    - debug: msg="Directory created"
      when: dir_status.changed
      
    - debug: msg="Directory is already created."
      when: 
        - dir_status.changed == false
        - dir_status.failed == false
      
    - name: Download the zip module
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /usr/bin/tools/aws-cli/awscli-bundle.zip
      register: aws_cli_download_bundle
      
    - debug: msg="AWS CLI installer is downloaded"
      when: aws_cli_download_bundle.changed
    
    - debug: msg="AWS CLI ZIP installer is already present. Moving to next task."
      when: 
        - aws_cli_download_bundle.changed == false
        - aws_cli_download_bundle.failed == false
        
    - name: Unarchive the installer.
      unarchive: 
        src: /usr/bin/tools/aws-cli/awscli-bundle.zip 
        dest: /usr/bin/tools/aws-cli
        remote_src: yes 
      when: (aws_cli_download_bundle.changed) or ((aws_cli_download_bundle.changed == false) and (aws_cli_download_bundle.failed == false))
      register: aws_cli_unarchive_installer
      
    - debug: msg="Unarchive zip installer successfuly"
      when: aws_cli_unarchive_installer.changed
    
    - debug: msg="Unarchived bundle already present"
      when:
        - aws_cli_unarchive_installer.changed == false
        - aws_cli_unarchive_installer.failed == false
        
    - name: Install awscli package.
      shell: /usr/bin/tools/aws-cli/aws/install -i /usr/bin/aws-cli -b /usr/bin
      args:
        creates: /usr/bin/aws
      register: aws_cli_install_package
      when: (aws_cli_unarchive_installer.changed) or ((aws_cli_unarchive_installer.changed == false) and (aws_cli_unarchive_installer.failed == false))
    
    - debug: msg="Package installed successfuly"
      when: aws_cli_install_package.changed
    
    - name: Check AWS CLI Version
      shell: aws --version
      register: aws_cli_version
      
    - debug: msg="AWS CLI is already installed with version {{aws_cli_version.stdout}}"
...
  